#---
# name: camera_action
#---

#Deriving the latest base image
FROM dustynv/opencv:4.8.1-r36.2.0
# FROM python:latest

# # Download Package Information
# RUN apt-get update -y && \
#     apt-get install -y \
#     tk 
    
#     #python-opencv

# RUN pip install serial



#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD ["bash"]
